import type { Tenant } from '@/types/tenant'
import type { UsageMetrics, SystemHealth } from '@/types/usage'


// Mock Super Admin User
export const mockSuperAdmin: any = {
  id: 1,
  email: "superadmin@visittrackingpro.com",
  full_name: "Super Administrator",
  role: "super_admin",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=superadmin",
  createdAt: new Date("2024-01-01"),
};

// Mock Plans
export const mockPlans: any[] = [
  {
    id: 'plan-1',
    name: 'Starter',
    description: 'Perfect for small teams getting started',
    monthlyPrice: 49,
    yearlyPrice: 490,
    maxUsers: 5,
    maxCustomers: 100,
    maxVisits: 500,
    isActive: true,
    tenantsCount: 25,
    features: [
      { name: 'Overview', included: true },
      { name: 'Tracking', included: true },
      { name: 'Customers', included: true },
      { name: 'Users', included: true },
      { name: 'Team', included: false },
      { name: 'Assignments', included: false },
      { name: 'My Tasks', included: false },
      { name: 'All Tasks', included: false },
      { name: 'Visits', included: true },
      { name: 'Feedback', included: false },
      { name: 'Reminders', included: false },
      { name: 'Resources', included: false },
      { name: 'Support', included: false },
      { name: 'Activity', included: false },
      { name: 'Reports', included: true },
    ],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'plan-2',
    name: 'Professional',
    description: 'For growing businesses with advanced needs',
    monthlyPrice: 149,
    yearlyPrice: 1490,
    maxUsers: 25,
    maxCustomers: 1000,
    maxVisits: 5000,
    isActive: true,
    tenantsCount: 42,
    features: [
      { name: 'Overview', included: true },
      { name: 'Tracking', included: true },
      { name: 'Customers', included: true },
      { name: 'Users', included: true },
      { name: 'Team', included: true },
      { name: 'Assignments', included: true },
      { name: 'My Tasks', included: true },
      { name: 'All Tasks', included: true },
      { name: 'Visits', included: true },
      { name: 'Feedback', included: true },
      { name: 'Reminders', included: true },
      { name: 'Resources', included: false },
      { name: 'Support', included: true },
      { name: 'Activity', included: true },
      { name: 'Reports', included: true },
    ],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'plan-3',
    name: 'Enterprise',
    description: 'Unlimited power for large organizations',
    monthlyPrice: 499,
    yearlyPrice: 4990,
    maxUsers: 100,
    maxCustomers: 10000,
    maxVisits: 50000,
    isActive: true,
    tenantsCount: 8,
    features: [
      { name: 'Overview', included: true },
      { name: 'Tracking', included: true },
      { name: 'Customers', included: true },
      { name: 'Users', included: true },
      { name: 'Team', included: true },
      { name: 'Assignments', included: true },
      { name: 'My Tasks', included: true },
      { name: 'All Tasks', included: true },
      { name: 'Visits', included: true },
      { name: 'Feedback', included: true },
      { name: 'Reminders', included: true },
      { name: 'Resources', included: true },
      { name: 'Support', included: true },
      { name: 'Activity', included: true },
      { name: 'Reports', included: true },
    ],
    createdAt: new Date('2024-01-15'),
  },
]

// Mock Tenants (Hybrid System - Both Centralized & Self-Hosted)
export const mockTenants: Tenant[] = [
  // Centralized Tenant 1
  {
    id: 'tenant-1',
    companyName: 'Acme Corporation',
    contactName: 'John Smith',
    contactEmail: 'john@acme.com',
    contactPhone: '+1-555-0101',
    status: 'active',
    planId: 'plan-2',
    planName: 'Professional',
    subscriptionStart: new Date('2024-01-20'),
    subscriptionEnd: new Date('2025-01-20'),
    totalUsers: 15,
    activeUsers: 12,
    mrr: 149,
    address: '123 Business St',
    city: 'New York',
    country: 'USA',
    createdAt: new Date('2024-01-20'),
    lastActivity: new Date('2024-11-29'),
    deploymentType: 'centralized',
    tenantDatabaseId: 'db-acme-001',
    apiEndpoint: 'https://api.visittrackingpro.com/tenant/acme',
  },
  // Self-Hosted Tenant 1
  {
    id: 'tenant-2',
    companyName: 'TechFlow Solutions',
    contactName: 'Sarah Johnson',
    contactEmail: 'sarah@techflow.io',
    contactPhone: '+1-555-0102',
    status: 'active',
    planId: 'plan-3',
    planName: 'Enterprise',
    subscriptionStart: new Date('2024-02-10'),
    subscriptionEnd: new Date('2025-02-10'),
    totalUsers: 50,
    activeUsers: 48,
    mrr: 0, // Self-hosted annual license
    address: '456 Tech Ave',
    city: 'San Francisco',
    country: 'USA',
    createdAt: new Date('2024-02-10'),
    lastActivity: new Date('2024-11-30'),
    deploymentType: 'self-hosted',
    licenseKey: 'VTP-2024-TECH-FLOW-AAAA-BBBB-CCCC',
    instanceUrl: 'https://visits.techflow.io',
    databaseType: 'postgresql',
    installationDate: new Date('2024-02-12'),
    lastHeartbeat: new Date('2024-11-30T14:30:00'),
    serverStatus: 'online',
    serverIp: '45.67.89.123',
  },
  // Centralized Tenant 2 (Trial)
  {
    id: 'tenant-3',
    companyName: 'Global Retail Inc',
    contactName: 'Mike Chen',
    contactEmail: 'mike@globalretail.com',
    contactPhone: '+1-555-0103',
    status: 'trial',
    planId: 'plan-1',
    planName: 'Starter',
    subscriptionStart: new Date('2024-11-15'),
    subscriptionEnd: new Date('2024-12-15'),
    totalUsers: 3,
    activeUsers: 3,
    mrr: 0,
    address: '789 Retail Blvd',
    city: 'Chicago',
    country: 'USA',
    createdAt: new Date('2024-11-15'),
    lastActivity: new Date('2024-11-30'),
    deploymentType: 'centralized',
    tenantDatabaseId: 'db-globalretail-003',
    apiEndpoint: 'https://api.visittrackingpro.com/tenant/globalretail',
  },
  // Self-Hosted Tenant 2 (Suspended - License Expired)
  {
    id: 'tenant-4',
    companyName: 'FastDelivery Co',
    contactName: 'Lisa Anderson',
    contactEmail: 'lisa@fastdelivery.com',
    contactPhone: '+1-555-0104',
    status: 'suspended',
    planId: 'plan-2',
    planName: 'Professional',
    subscriptionStart: new Date('2024-03-01'),
    subscriptionEnd: new Date('2024-11-01'), // Expired
    totalUsers: 20,
    activeUsers: 0,
    mrr: 0,
    address: '321 Logistics Way',
    city: 'Dallas',
    country: 'USA',
    createdAt: new Date('2024-03-01'),
    lastActivity: new Date('2024-10-15'),
    deploymentType: 'self-hosted',
    licenseKey: 'VTP-2024-FAST-DELV-XXXX-YYYY-ZZZZ',
    instanceUrl: 'https://tracking.fastdelivery.com',
    databaseType: 'mysql',
    installationDate: new Date('2024-03-03'),
    lastHeartbeat: new Date('2024-10-15T08:00:00'),
    serverStatus: 'offline',
    serverIp: '123.45.67.89',
  },
  // Centralized Tenant 3 (Active)
  {
    id: 'tenant-5',
    companyName: 'MediCare Services',
    contactName: 'Dr. James Wilson',
    contactEmail: 'james@medicare-services.com',
    contactPhone: '+1-555-0105',
    status: 'active',
    planId: 'plan-2',
    planName: 'Professional',
    subscriptionStart: new Date('2024-04-15'),
    subscriptionEnd: new Date('2025-04-15'),
    totalUsers: 18,
    activeUsers: 16,
    mrr: 149,
    address: '555 Health Plaza',
    city: 'Boston',
    country: 'USA',
    createdAt: new Date('2024-04-15'),
    lastActivity: new Date('2024-11-29'),
    deploymentType: 'centralized',
    tenantDatabaseId: 'db-medicare-005',
    apiEndpoint: 'https://api.visittrackingpro.com/tenant/medicare',
  },
  // Self-Hosted Tenant 3 (Recently Installed)
  {
    id: 'tenant-6',
    companyName: 'Saudi Logistics LLC',
    contactName: 'Ahmed Al-Rashid',
    contactEmail: 'ahmed@saudi-logistics.sa',
    contactPhone: '+966-555-0106',
    status: 'active',
    planId: 'plan-3',
    planName: 'Enterprise',
    subscriptionStart: new Date('2024-11-20'),
    subscriptionEnd: new Date('2025-11-20'),
    totalUsers: 75,
    activeUsers: 68,
    mrr: 0, // Annual license
    address: 'King Fahd Road',
    city: 'Riyadh',
    country: 'Saudi Arabia',
    createdAt: new Date('2024-11-20'),
    lastActivity: new Date('2024-11-30'),
    deploymentType: 'self-hosted',
    licenseKey: 'VTP-2024-SAUD-LOGI-PPPP-QQQQ-RRRR',
    instanceUrl: 'https://visits.saudi-logistics.sa',
    databaseType: 'postgresql',
    installationDate: new Date('2024-11-22'),
    lastHeartbeat: new Date('2024-11-30T16:45:00'),
    serverStatus: 'online',
    serverIp: '87.65.43.21',
  },
]

// Mock Invoices
export const mockInvoices: any[] = [
  {
    id: 'inv-1',
    tenantId: 'tenant-1',
    tenantName: 'Acme Corporation',
    amount: 149,
    status: 'paid',
    issueDate: new Date('2024-11-01'),
    dueDate: new Date('2024-11-15'),
    paidDate: new Date('2024-11-10'),
    description: 'Professional Plan - November 2024',
    planName: 'Professional',
    billingPeriod: 'November 2024',
  },
  {
    id: 'inv-2',
    tenantId: 'tenant-2',
    tenantName: 'TechFlow Solutions',
    amount: 499,
    status: 'paid',
    issueDate: new Date('2024-11-01'),
    dueDate: new Date('2024-11-15'),
    paidDate: new Date('2024-11-08'),
    description: 'Enterprise Plan - November 2024',
    planName: 'Enterprise',
    billingPeriod: 'November 2024',
  },
  {
    id: 'inv-3',
    tenantId: 'tenant-5',
    tenantName: 'MediCare Services',
    amount: 149,
    status: 'pending',
    issueDate: new Date('2024-11-01'),
    dueDate: new Date('2024-11-15'),
    description: 'Professional Plan - November 2024',
    planName: 'Professional',
    billingPeriod: 'November 2024',
  },
  {
    id: 'inv-4',
    tenantId: 'tenant-4',
    tenantName: 'FastDelivery Co',
    amount: 149,
    status: 'overdue',
    issueDate: new Date('2024-10-01'),
    dueDate: new Date('2024-10-15'),
    description: 'Professional Plan - October 2024',
    planName: 'Professional',
    billingPeriod: 'October 2024',
  },
]

// Mock Usage Metrics
export const mockUsageMetrics: UsageMetrics[] = [
  {
    tenantId: 'tenant-1',
    tenantName: 'Acme Corporation',
    currentUsers: 12,
    maxUsers: 25,
    currentCustomers: 450,
    maxCustomers: 1000,
    currentVisits: 2300,
    maxVisits: 5000,
    storageUsed: 2.5,
    storageLimit: 10,
    apiCallsThisMonth: 15000,
    healthStatus: 'healthy',
    lastChecked: new Date(),
  },
  {
    tenantId: 'tenant-2',
    tenantName: 'TechFlow Solutions',
    currentUsers: 48,
    maxUsers: 100,
    currentCustomers: 8500,
    maxCustomers: 10000,
    currentVisits: 42000,
    maxVisits: 50000,
    storageUsed: 45,
    storageLimit: 100,
    apiCallsThisMonth: 250000,
    healthStatus: 'warning',
    lastChecked: new Date(),
  },
  {
    tenantId: 'tenant-3',
    tenantName: 'Global Retail Inc',
    currentUsers: 3,
    maxUsers: 5,
    currentCustomers: 25,
    maxCustomers: 100,
    currentVisits: 80,
    maxVisits: 500,
    storageUsed: 0.2,
    storageLimit: 5,
    apiCallsThisMonth: 500,
    healthStatus: 'healthy',
    lastChecked: new Date(),
  },
  {
    tenantId: 'tenant-5',
    tenantName: 'MediCare Services',
    currentUsers: 16,
    maxUsers: 25,
    currentCustomers: 920,
    maxCustomers: 1000,
    currentVisits: 4800,
    maxVisits: 5000,
    storageUsed: 9.5,
    storageLimit: 10,
    apiCallsThisMonth: 48000,
    healthStatus: 'critical',
    lastChecked: new Date(),
  },
]

// Mock System Health
export const mockSystemHealth: SystemHealth = {
  uptime: 99.9,
  responseTime: 45,
  errorRate: 0.1,
  activeConnections: 342,
}

// Mock Support Tickets
export const mockSupportTickets: any[] = [
  {
    id: 'ticket-1',
    tenantId: 'tenant-1',
    tenantName: 'Acme Corporation',
    subject: 'Unable to export reports',
    description: 'When trying to export monthly reports, the system shows an error message.',
    status: 'open',
    priority: 'high',
    category: 'Technical',
    createdBy: 'john@acme.com',
    assignedTo: 'Super Admin',
    replies: [
      {
        id: 'reply-1',
        ticketId: 'ticket-1',
        authorId: 'john@acme.com',
        authorName: 'John Smith',
        authorRole: 'tenant',
        message: 'When trying to export monthly reports, the system shows an error message. Can you help?',
        createdAt: new Date('2024-11-28T10:00:00'),
        attachments: ['error-screenshot.png', 'report-settings.pdf'],
      },
    ],
    createdAt: new Date('2024-11-28T10:00:00'),
    updatedAt: new Date('2024-11-28T10:00:00'),
  },
  {
    id: 'ticket-2',
    tenantId: 'tenant-3',
    tenantName: 'Global Retail Inc',
    subject: 'Request for plan upgrade',
    description: 'We would like to upgrade from Starter to Professional plan.',
    status: 'in-progress',
    priority: 'medium',
    category: 'Billing',
    createdBy: 'mike@globalretail.com',
    assignedTo: 'Super Admin',
    replies: [
      {
        id: 'reply-2',
        ticketId: 'ticket-2',
        authorId: 'mike@globalretail.com',
        authorName: 'Mike Chen',
        authorRole: 'tenant',
        message: 'We would like to upgrade from Starter to Professional plan. What are the next steps?',
        createdAt: new Date('2024-11-27T14:30:00'),
      },
      {
        id: 'reply-3',
        ticketId: 'ticket-2',
        authorId: 'superadmin',
        authorName: 'Super Admin',
        authorRole: 'super_admin',
        message: 'Thank you for your interest in upgrading! I will process this request and send you the updated invoice.',
        createdAt: new Date('2024-11-27T15:00:00'),
        attachments: ['professional-plan-details.pdf', 'upgrade-invoice.pdf'],
      },
    ],
    createdAt: new Date('2024-11-27T14:30:00'),
    updatedAt: new Date('2024-11-27T15:00:00'),
  },
  {
    id: 'ticket-3',
    tenantId: 'tenant-5',
    tenantName: 'MediCare Services',
    subject: 'Approaching usage limits',
    description: 'We are approaching our customer and visit limits. Need guidance.',
    status: 'resolved',
    priority: 'urgent',
    category: 'Account',
    createdBy: 'james@medicare-services.com',
    assignedTo: 'Super Admin',
    replies: [
      {
        id: 'reply-4',
        ticketId: 'ticket-3',
        authorId: 'james@medicare-services.com',
        authorName: 'Dr. James Wilson',
        authorRole: 'tenant',
        message: 'We are approaching 95% of our customer and visit limits. What happens when we reach the limit?',
        createdAt: new Date('2024-11-26T09:00:00'),
      },
      {
        id: 'reply-5',
        ticketId: 'ticket-3',
        authorId: 'superadmin',
        authorName: 'Super Admin',
        authorRole: 'super_admin',
        message: 'I recommend upgrading to the Enterprise plan for unlimited customers and visits. I can help you with that transition.',
        createdAt: new Date('2024-11-26T09:30:00'),
      },
    ],
    createdAt: new Date('2024-11-26T09:00:00'),
    updatedAt: new Date('2024-11-26T09:30:00'),
    resolvedAt: new Date('2024-11-26T09:30:00'),
  },
]

// Mock Notifications
export const mockNotifications: any[] = [
  {
    id: 'notif-1',
    type: 'success',
    title: 'New Tenant Signup',
    message: 'Global Retail Inc has signed up for the Starter plan',
    read: false,
    createdAt: new Date('2024-11-30T08:00:00'),
    tenantId: 'tenant-3',
  },
  {
    id: 'notif-2',
    type: 'warning',
    title: 'Payment Overdue',
    message: 'FastDelivery Co has an overdue invoice of ر.س149',
    read: false,
    createdAt: new Date('2024-11-29T10:00:00'),
    tenantId: 'tenant-4',
  },
  {
    id: 'notif-3',
    type: 'info',
    title: 'Usage Alert',
    message: 'MediCare Services is approaching usage limits (95%)',
    read: true,
    createdAt: new Date('2024-11-28T14:00:00'),
    tenantId: 'tenant-5',
  },
  {
    id: 'notif-4',
    type: 'error',
    title: 'System Alert',
    message: 'High API error rate detected for TechFlow Solutions',
    read: true,
    createdAt: new Date('2024-11-27T16:00:00'),
    tenantId: 'tenant-2',
  },
]

// Mock Audit Logs
export const mockAuditLogs: any[] = [
  {
    id: 'audit-1',
    adminId: '1',
    adminName: 'Super Administrator',
    action: 'tenant_created',
    entityType: 'Tenant',
    entityId: 'tenant-3',
    entityName: 'Global Retail Inc',
    details: 'Created new tenant with Starter plan',
    ipAddress: '192.168.1.1',
    createdAt: new Date('2024-11-30T08:00:00'),
  },
  {
    id: 'audit-2',
    adminId: '1',
    adminName: 'Super Administrator',
    action: 'tenant_suspended',
    entityType: 'Tenant',
    entityId: 'tenant-4',
    entityName: 'FastDelivery Co',
    details: 'Suspended tenant due to non-payment',
    ipAddress: '192.168.1.1',
    createdAt: new Date('2024-11-29T11:00:00'),
  },
  {
    id: 'audit-3',
    adminId: '1',
    adminName: 'Super Administrator',
    action: 'plan_updated',
    entityType: 'Plan',
    entityId: 'plan-2',
    entityName: 'Professional',
    details: 'Updated pricing for Professional plan',
    ipAddress: '192.168.1.1',
    createdAt: new Date('2024-11-28T15:30:00'),
  },
  {
    id: 'audit-4',
    adminId: '1',
    adminName: 'Super Administrator',
    action: 'invoice_created',
    entityType: 'Invoice',
    entityId: 'inv-3',
    entityName: 'MediCare Services - November 2024',
    details: 'Generated invoice for November billing cycle',
    ipAddress: '192.168.1.1',
    createdAt: new Date('2024-11-01T00:00:00'),
  },
  {
    id: 'audit-5',
    adminId: '1',
    adminName: 'Super Administrator',
    action: 'ticket_resolved',
    entityType: 'Support Ticket',
    entityId: 'ticket-3',
    entityName: 'Approaching usage limits',
    details: 'Resolved support ticket and recommended plan upgrade',
    ipAddress: '192.168.1.1',
    createdAt: new Date('2024-11-26T09:30:00'),
  },
]
